import './globals.css'
import type { Metadata } from 'next'
import { Inter, Patrick_Hand_SC } from 'next/font/google'
import { Patrick_Hand } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const Patrick = Patrick_Hand({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
        </body>
    </html>
  )
}
